
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 03 02:26:18 CST 2022
//----------------------------------------------------

package scaner_01;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAS_ = 18;
  public static final int MENORQUE_ = 35;
  public static final int LETRALMAY_ = 51;
  public static final int CONJUNTO_ = 6;
  public static final int LETRATMIN_ = 91;
  public static final int LETRADMIN_ = 75;
  public static final int LETRAQMAY_ = 56;
  public static final int BARRAINVERTIDA_ = 67;
  public static final int LLAVEA_ = 98;
  public static final int PUNTOYCOMA_ = 34;
  public static final int LETRAAMAY_ = 40;
  public static final int LETRAYMIN_ = 96;
  public static final int ACENTOGRAVE_ = 71;
  public static final int COMILLADOBLETEXTO_ = 105;
  public static final int LETRAIMIN_ = 80;
  public static final int LETRAVMAY_ = 61;
  public static final int LETRAFMAY_ = 45;
  public static final int LETRANMIN_ = 85;
  public static final int TRES_ = 26;
  public static final int LETRAKMAY_ = 50;
  public static final int GUIONBAJO_ = 70;
  public static final int MAYORQUE_ = 37;
  public static final int LETRASMIN_ = 90;
  public static final int COMILLASIMPLE_ = 14;
  public static final int LETRACMIN_ = 74;
  public static final int LETRAPMAY_ = 55;
  public static final int OCHO_ = 31;
  public static final int CERO_ = 23;
  public static final int LETRAXMIN_ = 95;
  public static final int LETRAHMIN_ = 79;
  public static final int ERROR = 106;
  public static final int IGUAL_ = 36;
  public static final int LETRAUMAY_ = 60;
  public static final int DOS_ = 25;
  public static final int LETRAEMAY_ = 44;
  public static final int COMILLASIMPLETEXTO_ = 104;
  public static final int LETRAMMIN_ = 84;
  public static final int LETRAZMAY_ = 65;
  public static final int CINCO_ = 28;
  public static final int LETRAJMAY_ = 49;
  public static final int AMPERSAND_ = 13;
  public static final int CUATRO_ = 27;
  public static final int LETRARMIN_ = 89;
  public static final int LETRABMIN_ = 73;
  public static final int INTERROGACION_ = 38;
  public static final int LETRAOMAY_ = 54;
  public static final int IDENTIFICADOR_ = 4;
  public static final int UNO_ = 24;
  public static final int TILDE_ = 101;
  public static final int LETRAWMIN_ = 94;
  public static final int PARENTESISABIERTO_ = 15;
  public static final int LETRAGMIN_ = 78;
  public static final int PUNTO_ = 21;
  public static final int LETRATMAY_ = 59;
  public static final int NUEVE_ = 32;
  public static final int LETRADMAY_ = 43;
  public static final int NUMERAL_ = 10;
  public static final int COMILLADOBLE_ = 9;
  public static final int LETRALMIN_ = 83;
  public static final int MENOS_ = 20;
  public static final int LETRAYMAY_ = 64;
  public static final int LETRAIMAY_ = 48;
  public static final int ASIGNACIONCONJUNTO_ = 102;
  public static final int LETRAQMIN_ = 88;
  public static final int LETRAAMIN_ = 72;
  public static final int SIETE_ = 30;
  public static final int BARRA_ = 22;
  public static final int EOF = 0;
  public static final int LETRANMAY_ = 53;
  public static final int LETRAVMIN_ = 93;
  public static final int SALTODELINEATEXTO_ = 103;
  public static final int BARRAVERTICAL_ = 99;
  public static final int LETRAFMIN_ = 77;
  public static final int LETRASMAY_ = 58;
  public static final int LETRACMAY_ = 42;
  public static final int ACENTOCIRCUNFLEJO_ = 69;
  public static final int LETRAKMIN_ = 82;
  public static final int NUMEROCOMPUESTO_ = 5;
  public static final int ARROBA_ = 39;
  public static final int error = 1;
  public static final int LETRAXMAY_ = 63;
  public static final int LLAVEC_ = 100;
  public static final int LETRAHMAY_ = 47;
  public static final int LETRAPMIN_ = 87;
  public static final int DOSPUNTOS_ = 33;
  public static final int PORCENTAJE_ = 12;
  public static final int CORCHETEABIERTO_ = 66;
  public static final int LETRAMMAY_ = 52;
  public static final int LETRAUMIN_ = 92;
  public static final int CORCHECERRADO_ = 68;
  public static final int LETRAEMIN_ = 76;
  public static final int LETRARMAY_ = 57;
  public static final int PARENTESISCERRADO_ = 16;
  public static final int SEIS_ = 29;
  public static final int ASTERISCO_ = 17;
  public static final int LETRABMAY_ = 41;
  public static final int COMENTUNILINEA_ = 2;
  public static final int LETRAZMIN_ = 97;
  public static final int LETRAJMIN_ = 81;
  public static final int DOLAR_ = 11;
  public static final int LETRAWMAY_ = 62;
  public static final int LETRAGMAY_ = 46;
  public static final int ADMIRACION_ = 8;
  public static final int COMA_ = 19;
  public static final int COMENTMULTILINEA_ = 3;
  public static final int LETRAOMIN_ = 86;
  public static final int SEPARADOR_ = 7;
}

